const activities = [
  { name: "Go for a walk", place: "outdoor", mood: "calm" },
  { name: "Ride a bicycle", place: "outdoor", mood: "active" },
  { name: "Have a picnic", place: "outdoor", mood: "calm" },
  { name: "Play badminton", place: "outdoor", mood: "active" },
  { name: "Watch the sunset", place: "outdoor", mood: "calm" },
  { name: "Go hiking", place: "outdoor", mood: "active" },
  { name: "Visit a botanical garden", place: "outdoor", mood: "calm" },
  { name: "Play frisbee", place: "outdoor", mood: "active" },
  { name: "Sit by the lake", place: "outdoor", mood: "calm" },
  { name: "Go roller skating", place: "outdoor", mood: "active" },

  { name: "Read a book", place: "indoor", mood: "calm" },
  { name: "Do yoga", place: "indoor", mood: "calm" },
  { name: "Dance at home", place: "indoor", mood: "active" },
  { name: "Try a home workout", place: "indoor", mood: "active" },
  { name: "Watch a movie", place: "indoor", mood: "calm" },
  { name: "Do a stretching session", place: "indoor", mood: "active" },
  { name: "Listen to music", place: "indoor", mood: "calm" },
  { name: "Try a cardio workout", place: "indoor", mood: "active" },
  { name: "Journal your thoughts", place: "indoor", mood: "calm" },
  { name: "Learn a dance routine", place: "indoor", mood: "active" },

  { name: "Visit a museum", place: "indoor", mood: "calm" },
  { name: "Go bowling", place: "indoor", mood: "active" },
  { name: "Go to the cinema", place: "indoor", mood: "calm" },
  { name: "Climb at an indoor gym", place: "indoor", mood: "active" },
  { name: "Spend time in a bookstore", place: "indoor", mood: "calm" },
  { name: "Try an escape room", place: "indoor", mood: "active" },
  { name: "Sit in a cozy café", place: "indoor", mood: "calm" },
  { name: "Go to the gym", place: "indoor", mood: "active" },

  { name: "Take a boat ride", place: "outdoor", mood: "calm" },
  { name: "Play football", place: "outdoor", mood: "active" },
  { name: "Go fishing", place: "outdoor", mood: "calm" },
  { name: "Walk a long scenic route", place: "outdoor", mood: "active" },
  { name: "Visit a quiet beach", place: "outdoor", mood: "calm" },
  { name: "Try paddleboarding", place: "outdoor", mood: "active" },
  { name: "Sit in a garden", place: "outdoor", mood: "calm" },
  { name: "Play mini golf", place: "outdoor", mood: "active" },
  { name: "Take a slow bike ride", place: "outdoor", mood: "calm" },
  { name: "Explore a new neighborhood", place: "outdoor", mood: "active" },
  { name: "Watch the stars", place: "outdoor", mood: "calm" },
  { name: "Go kayaking", place: "outdoor", mood: "active" }
];